// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcrTx8cqMmm66zt5rmDOfxix5oB2DdSUA',
    appId: '1:104865382995:web:7abffd334613dd2fc1fca6',
    messagingSenderId: '104865382995',
    projectId: 'photo-reader-9fc8d',
    authDomain: 'photo-reader-9fc8d.firebaseapp.com',
    storageBucket: 'photo-reader-9fc8d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATWLRcrMHMUwtABtktgOXelR0Pvc2JkwQ',
    appId: '1:104865382995:android:26f39299a6076583c1fca6',
    messagingSenderId: '104865382995',
    projectId: 'photo-reader-9fc8d',
    storageBucket: 'photo-reader-9fc8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR5Cz4uVGy2JDQ-f59aRWIG4LWL6bOnrc',
    appId: '1:104865382995:ios:c783c9eee19ef6c5c1fca6',
    messagingSenderId: '104865382995',
    projectId: 'photo-reader-9fc8d',
    storageBucket: 'photo-reader-9fc8d.appspot.com',
    iosClientId: '104865382995-2qoc1t19j4s3bu4rmj6cenfked1us2t8.apps.googleusercontent.com',
    iosBundleId: 'cpp.edu.realFirstFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR5Cz4uVGy2JDQ-f59aRWIG4LWL6bOnrc',
    appId: '1:104865382995:ios:33ed81956c618ffcc1fca6',
    messagingSenderId: '104865382995',
    projectId: 'photo-reader-9fc8d',
    storageBucket: 'photo-reader-9fc8d.appspot.com',
    iosClientId: '104865382995-banlht56rd8t7dd82bfjk9s0ukk3e8s8.apps.googleusercontent.com',
    iosBundleId: 'cpp.edu.realFirstFlutterProject.RunnerTests',
  );
}
